# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/zybo.xdc

# Block Designs: bd/poxi_design/poxi_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==poxi_design || ORIG_REF_NAME==poxi_design}]

# IP: bd/poxi_design/ip/poxi_design_processing_system7_0_0/poxi_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==poxi_design_processing_system7_0_0 || ORIG_REF_NAME==poxi_design_processing_system7_0_0}]

# IP: bd/poxi_design/ip/poxi_design_POXI_0_0/poxi_design_POXI_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==poxi_design_POXI_0_0 || ORIG_REF_NAME==poxi_design_POXI_0_0}]

# IP: bd/poxi_design/ip/poxi_design_ps7_0_axi_periph_0/poxi_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==poxi_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==poxi_design_ps7_0_axi_periph_0}]

# IP: bd/poxi_design/ip/poxi_design_rst_ps7_0_100M_0/poxi_design_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==poxi_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==poxi_design_rst_ps7_0_100M_0}]

# IP: bd/poxi_design/ip/poxi_design_TFT_SPI_DISPLAY_240x320_0_0/poxi_design_TFT_SPI_DISPLAY_240x320_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==poxi_design_TFT_SPI_DISPLAY_240x320_0_0 || ORIG_REF_NAME==poxi_design_TFT_SPI_DISPLAY_240x320_0_0}]

# IP: bd/poxi_design/ip/poxi_design_xbar_0/poxi_design_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==poxi_design_xbar_0 || ORIG_REF_NAME==poxi_design_xbar_0}]

# IP: bd/poxi_design/ip/poxi_design_auto_pc_0/poxi_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==poxi_design_auto_pc_0 || ORIG_REF_NAME==poxi_design_auto_pc_0}]

# XDC: bd/poxi_design/ip/poxi_design_processing_system7_0_0/poxi_design_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==poxi_design_processing_system7_0_0 || ORIG_REF_NAME==poxi_design_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/poxi_design/ip/poxi_design_rst_ps7_0_100M_0/poxi_design_rst_ps7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==poxi_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==poxi_design_rst_ps7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/poxi_design/ip/poxi_design_rst_ps7_0_100M_0/poxi_design_rst_ps7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==poxi_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==poxi_design_rst_ps7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/poxi_design/ip/poxi_design_rst_ps7_0_100M_0/poxi_design_rst_ps7_0_100M_0_ooc.xdc

# XDC: bd/poxi_design/ip/poxi_design_xbar_0/poxi_design_xbar_0_ooc.xdc

# XDC: bd/poxi_design/ip/poxi_design_auto_pc_0/poxi_design_auto_pc_0_ooc.xdc

# XDC: bd/poxi_design/poxi_design_ooc.xdc
