# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Yarib/poxi/poxi.cache/wt [current_project]
set_property parent.project_path C:/Users/Yarib/poxi/poxi.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths c:/zybo_projects/ip_repo [current_project]
set_property ip_output_repo c:/Users/Yarib/poxi/poxi.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/Yarib/poxi/poxi.srcs/sources_1/bd/poxi_design/hdl/poxi_design_wrapper.vhd
add_files C:/Users/Yarib/poxi/poxi.srcs/sources_1/bd/poxi_design/poxi_design.bd
set_property used_in_implementation false [get_files -all c:/Users/Yarib/poxi/poxi.srcs/sources_1/bd/poxi_design/ip/poxi_design_processing_system7_0_0/poxi_design_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Yarib/poxi/poxi.srcs/sources_1/bd/poxi_design/ip/poxi_design_rst_ps7_0_100M_0/poxi_design_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Yarib/poxi/poxi.srcs/sources_1/bd/poxi_design/ip/poxi_design_rst_ps7_0_100M_0/poxi_design_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Yarib/poxi/poxi.srcs/sources_1/bd/poxi_design/ip/poxi_design_rst_ps7_0_100M_0/poxi_design_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Yarib/poxi/poxi.srcs/sources_1/bd/poxi_design/ip/poxi_design_xbar_0/poxi_design_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Yarib/poxi/poxi.srcs/sources_1/bd/poxi_design/ip/poxi_design_auto_pc_0/poxi_design_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/Yarib/poxi/poxi.srcs/sources_1/bd/poxi_design/poxi_design_ooc.xdc]
set_property is_locked true [get_files C:/Users/Yarib/poxi/poxi.srcs/sources_1/bd/poxi_design/poxi_design.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Yarib/poxi/poxi.srcs/constrs_1/imports/new/zybo.xdc
set_property used_in_implementation false [get_files C:/Users/Yarib/poxi/poxi.srcs/constrs_1/imports/new/zybo.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top poxi_design_wrapper -part xc7z010clg400-1


write_checkpoint -force -noxdef poxi_design_wrapper.dcp

catch { report_utilization -file poxi_design_wrapper_utilization_synth.rpt -pb poxi_design_wrapper_utilization_synth.pb }
